import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";

const monserrat = Poppins({
  variable: "--font-poppins",
  weight: "400", // Adjust the weight as needed
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${monserrat.variable} bg-gray-50 h-screen light`}

      >
        <Header />
        {children}

      </body>
    </html>
  );
}
